////// data estatica JSON

let dataFood = [
  {
    id: 1,
    name: "Frutillas",
    description: "Frutillas disecadas super dulces.",
    image: "./images/food1.jpg",
    price: 250,
    count: 1,
  },
  {
    id: 2,
    name: "Biscuit",
    description: "Galletas nutri choco y crema.",
    image: "./images/food2.jpg",
    price: 200,
    count: 1,
  },
  {
    id: 3,
    name: "Sopa",
    description: "Sopa de verduras con vasito de regalo.",
    image: "./images/food3.png",
    price: 300,
    count: 1,
  },
  {
    id: 4,
    name: "Cookie",
    description: "Galletita rellena doble crema.",
    image: "./images/food4.jpg",
    price: 200,
    count: 1,
  },
  {
    id: 5,
    name: "Nutri pure",
    description: "Exquisito pure de papas.",
    image: "./images/food5.jpg",
    price: 180,
    count: 1,
  },
  {
    id: 6,
    name: "Cookie Ice",
    description: "Tu postre ideal para el espacio!",
    image: "./images/food6.jpg",
    price: 230,
    count: 1,
  },
  {
    id: 7,
    name: "Ciruela",
    description: "Ciruelas disecadas en gajos.",
    image: "./images/food7.png",
    price: 180,
    count: 1,
  },
  {
    id: 8,
    name: "Queso",
    description: "Fetas de queso de cabra.",
    image: "./images/food8.jpg",
    price: 270,
    count: 1,
  },
];
